### PR TITLE
Add pr_check and build_deploy scripts

### PR DESCRIPTION
**Pull request by karelhala**
### Add image build scripts

Since hac-core is onboarded to app-sre build process, let's add deploy scripts (for both PR and main merges).

### CODE REVIEW

**Comment by karelhala** [comment]
ping @BlakeHolifield can you please take a look? I've swaped assignment to `WORKSPACE` as it makes a bit more sense this way. Also added `IQE_PLUGINS` variable not sure if we need it now or not.

**Review by BlakeHolifield — APPROVED** [review]

**Review by andrewballantyne — APPROVED** [review]

**Comment by andrewballantyne** [comment]
Hmm, I do not have read access on the `ci.ext.devshift.net PR Build` check 🤔

**Pull request merged**
