### PR TITLE
Test plural hook useK8sWatchResources using testK8s

### PR DESCRIPTION
**Pull request by vidyanambiar**
To test:
```bash
cd frontend
# Install latest lib-utils package version 1.0.0-alpha8
yarn install
ENVIRONMENT=prod yarn dev
```
In the browser, open: https://prod.foo.redhat.com:1337/beta/hac/testK8s

Screen Shot 2022-04-14 at 11 49 56 AM

Screen Shot 2022-04-14 at 11 52 10 AM

### CODE REVIEW

**Review by karelhala — APPROVED** [review]
Looking good! Can you add `apiPriorityList` to appConfig as well? Similiar to https://github.com/openshift/hac-core/pull/66/files#diff-c28e0f570141ce9bac5bcbb0b9e19bbeed46fe899b1bf13bbdefda31854c7fbcR27

**Review by karelhala — APPROVED** [review]
/lgtm

**Comment by florkbr** [comment]
Looks good to me too :)

**Pull request merged**
