### PR TITLE
[HAC 267] Update createStore to pass in sharedScope object over function

### PR DESCRIPTION
**Pull request by florkbr**
We introduced a breaking change in the latest SDK while adding the sample app in [this PR](https://github.com/openshift/dynamic-plugin-sdk/pull/74). This should resolve the issue around the sharedScope object.

See https://issues.redhat.com/browse/HAC-267

### CODE REVIEW

**Comment by karelhala** [comment]
@florkbr the prow is failing because of missing type, here is a PR to re-export it once again https://github.com/openshift/dynamic-plugin-sdk/pull/89

**Comment by florkbr** [comment]
@karelhala sorry - I forgot I had this open! I've published your changes in alpha7 and bumped in this PR. Please re-review!

**Review by karelhala — APPROVED** [review]
/lgtm

**Pull request merged**
